### ISSUE TITLE
Return minified json from app endpoints

### ISSUE THREAD

**Issue by kylebarron** [developmentseed/cogeo-mosaic-tiler#16]
Several app endpoints return JSON. It might be nice to return minified JSON, for a small improvement in network bandwidth. It consists of literally just replacing:
```py
json.dumps(dict)
```
with
```py
json.dumps(dict, separators=(',', ':'))
```

**Comment by vincentsarago** [comment]
done in https://github.com/developmentseed/cogeo-mosaic-tiler/pull/19/commits/cf142d6f8d24691789c89c441b7ea45ac5694307
