### ISSUE TITLE
`/info` will not work with DynamoDB

### ISSUE THREAD

**Issue by vincentsarago** [developmentseed/cogeo-mosaic-tiler#18]
https://github.com/developmentseed/cogeo-mosaic-tiler/blob/05eb109d5bd9221bf6287440f53025e6ad84ee78/cogeo_mosaic_tiler/handlers/app.py#L204-L222

@kylebarron, as for the `overview` cli we are fetching the quadkey list to get info from the COG (dtype and band names). I think for now I'll just add a test so user can pass a `quadkey` if they try to use dynamoDB backend. 

Maybe we could add `dtype` and `layers` in the specification 🤔

**Comment by vincentsarago** [comment]
FYI:
- `dtype` is usually used to determine if we need rescaling (not needed if data is stored as byte)
- `layer_names` is used for the `mvt` where we need to know the layer names to display

**Comment by kylebarron** [comment]
`/info` could return whatever data exists, so `dtype` and `layer_names` could just be missing when a dynamodb endpoint is used.
