### ISSUE TITLE
Coercing float to float?

### ISSUE THREAD

**Issue by kylebarron** [developmentseed/cogeo-mosaic-tiler#7]
Here you're coercing a float to float...
https://github.com/developmentseed/cogeo-mosaic-tiler/blob/cf0587181325ab4897df2e7c7f7979bbe56b2e46/cogeo_mosaic_tiler/handlers/app.py#L97-L99

Do you mean
```py
min_tile_cover = ( 
     float(min_tile_cover) if min_tile_cover is not None else min_tile_cover 
) 
```
?

**Comment by vincentsarago** [comment]
🤦‍♂ I guess

**Comment by vincentsarago** [comment]
an other example that we need better tests

**Comment by vincentsarago** [comment]
done in #19
